---
name: Rotate Credential

on:
  workflow_dispatch:
  repository_dispatch:
    types: [rotate-credential]

permissions:
  id-token: write
  contents: read
  packages: read

env:
  HCP_IDP: ${{ vars.HCP_IDP }}
  HCP_CLI_VERSION: ${{ vars.HCP_CLI_VERSION || 'latest' }}
  HCP_PROJECT: ${{ vars.HCP_PROJECT }}
  HCP_APP: ${{ vars.HCP_APP || 'hcp-terraform-user-accounts' }}
  HCP_SECRET: ${{ vars.HCP_SECRET || 'tfc_provisioning2' }}

jobs:
  rotate-credential:
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@v2

      - id: hcp-download
        name: Download HCP CLI
        uses: hashicorp/hcp-setup-action@v0
        with:
          version: ${{ env.HCP_CLI_VERSION}}

      - id: hcp-auth
        name: Authenticate to HCP
        uses: hashicorp/hcp-auth-action@v0
        with:
          workload_identity_provider: ${{ env.HCP_IDP }}

      - id: hcp-get-secrets
        name: HCP Get Secrets
        uses: dustindortch/gha-hcp-vault-get-secret@b05104c05932cdce6125f2dbfb5091624063ac83
        with:
          name: ${{ env.HCP_SECRET }}
          app: ${{ env.HCP_APP }}
          project: ${{ env.HCP_PROJECT }}


      - name: Rotate credentials
        run: |
          echo "Rotating credentials..."
          # Add your credential rotation logic here
...